### PR TITLE
Add additional template types.

### PR DESCRIPTION
**Pull request by dwt**
Hi there,

I needed additional template types (only the image) and then further to be able to provide my own, so I added them. Would you be willing to accept those as a pull request?

### CODE REVIEW

**Comment by humrochagf** [comment]
Of course that was an awesome contribution, thank you :)

I will add the description at the readme, make the version bump and publish, so you can get it directly from the lektor plugin manager

**Comment by humrochagf** [comment]
@dwt Can you describe me the caller use case so i can add it to the docs? And the template option caller doesn't seems to do anything, i think we can remove it and keep caller only as argument

**Comment by dwt** [comment]
Sure, I use it like this. In effect it allows me to completely customize the template, without having to touch the plugin.

```html
  <li class="nav-item license">
    {% call(type, version, locale, size, message, license) render_cc_license('by-sa', size='normal', template='caller') %}
      <a class="nav-item" style="" rel="license" target="_blank" href="http://creativecommons.org/licenses/{{type}}/{{version}}/deed.{{locale}}">
        <img class="" alt="Creative Commons {{type}}" style="border-width:0" src="https://i.creativecommons.org/l/{{type}}/{{version}}/{{size}}.png" />
      </a>
    {% endcall %}
  </li>
```

**Comment by dwt** [comment]
So in effect, I inject the template as a callable into the plugin.

**Pull request merged**
