### PR TITLE
[WIP] Auto download creative commons logos and use them

### PR DESCRIPTION
**Pull request by dwt**
regarding #3 I've come up with this code which I'm not at all sure is the idiomatic way to use lector here. It does seem to work up to a point, but of course doesn't account for python2 yet and is missing error handling.

Still, I'd love some feedback on it. What do you think?

### CODE REVIEW

**Comment by humrochagf** [comment]
@dwt that was an excellent idea.
I made a branch from your PR and added some code to run at both python versions, changed the artifact to run as as decorator and to only download the icon used instead of download all icons: https://github.com/humrochagf/lektor-creative-commons/pull/5
I also changed the icon_path to be an variable, so we can add it as an external parameter for custom icons after.

**Comment by dwt** [comment]
Wow, that sounds great! I'll have a look tomorrow!

**Comment by dwt** [comment]
I lied, I looked immediately. I quite like it! Though testing has to wait till tomorrow. :-)

**Comment by dwt** [comment]
I'm currently testing your branch and think it's quite nice. Some thoughts I have had over the last two days:

* It might be easier to just ship the Creative Commons logos with the plugin, and then use https://www.getlektor.com/docs/api/build/artifact/replace-with-file/ to copy them over. That would also give a maybe better `sources` argument to `@ctx.sub_artifact` - however I'm not sure I understand this API correctly, as the exact meaning of this argument still escapes me. Still, less network traffic and less source for errors might be a good idea (and the code might be simpler that way). Also this would allow building without internet access, which is probably a good thing.
* Not sure why, but it seems (from the build output) that the artifact (`static/lektor-creative-commons/by-sa/4.0/88x31.png` in my case) is built every time a page includes it. At least thats what this output seems to suggest.
  
        U blog/2008/5/piratenpartei-treibt-dollarkurs-in-die-ho-he/index.html
        U static/lektor-creative-commons/by-sa/4.0/88x31.png
        U blog/2008/5/regeln/index.html
        U static/lektor-creative-commons/by-sa/4.0/88x31.png
        U blog/2008/5/der-traum-vom-fliegen/index.html
        U static/lektor-creative-commons/by-sa/4.0/88x31.png
        U blog/2008/5/parteitagsstimmung/index.html
        U static/lektor-creative-commons/by-sa/4.0/88x31.png
        U blog/2008/5/was-ist-die-piratenpartei/index.html
        U static/lektor-creative-commons/by-sa/4.0/88x31.png
        U blog/2008/5/experimentalphysik-und-programmieren/index.html
        U static/lektor-creative-commons/by-sa/4.0/88x31.png
        U blog/2008/5/wann-darf-man-eigentlich/index.html
        U static/lektor-creative-commons/by-sa/4.0/88x31.png
        U blog/2008/5/wie-man-die-lo-schen-taste-implementiert/index.html
        U static/lektor-creative-commons/by-sa/4.0/88x31.png
        U blog/2008/5/mein-name-ist-martin-und-ich-bin-ein-pirat/index.html
        U static/lektor-creative-commons/by-sa/4.0/88x31.png
        U blog/2008/5/den-mobile-monday/index.html
        U static/lektor-creative-commons/by-sa/4.0/88x31.png
        U blog/2008/5/rechtstaat-und-demonstration/index.html
        U static/lektor-creative-commons/by-sa/4.0/88x31.png

  Do you understand how the build-system is supposed to work? The Build-Function already short-circuits in this circumstances, but it seems there is no way to tell lector about this?
* Even though (ctx.sub_artifact)[https://www.getlektor.com/docs/api/build/context/sub-artifact/] seems to do the trick to introduce a new file, I'm not convinced that it's actually the right approach to take here, as the artifact we create is not actually _contained_ within the artifact that triggers it. I'm not aware of any other method to achieve what we want though. Maybe the more correct way to use it would be to collect all pages that reference it, and then hand all of them in as `sources` to the sub-artifact? I'm not even sure this is possible though. Maybe by recording the sources and then adding a `sub_artifact()` with all the collected sources in the `after-build` event?

Well, sorry for providing only questions and mostly no answers. Still this is going in a great direction!

**Comment by humrochagf** [comment]
Yeah, since you have a reference to the file on each post you have to check that artifact for every page, but these highlighted line (https://github.com/humrochagf/lektor-creative-commons/pull/5/commits/d5b123aa27e2ba89b20adc02c1178ad66de68ffd#diff-d99607b2a0f95bd3280d6862de9cf807R128) prevents us from downloading the image again.

I'm not sure about the sources parameter, but checking its usage on lektor code https://github.com/lektor/lektor/blob/bc3064b8dc0c45b0c6274470c4d9a95e8bf4866c/lektor/imagetools.py#L434-L467 it seems to store the source where the images goes, maybe to prevent this consecutive triggering of the image build.

And thinking about making a more stable plugin that runs even offline, shipping the icons is probably the right approach to that.

**Comment by dwt** [comment]
> Yeah, since you have a reference to the file on each post you have to check that artifact for every page, but these highlighted line (d5b123a#diff-d99607b2a0f95bd3280d6862de9cf807R128 <https://github.com/humrochagf/lektor-creative-commons/commit/d5b123aa27e2ba89b20adc02c1178ad66de68ffd#diff-d99607b2a0f95bd3280d6862de9cf807R128>) prevents us from downloading the image again.
> 
Yes, that does work, however it still spams the build log (for me every other line is for an image download) which is likely not as intended.
> I'm not sure about the sources parameter, but checking its usage on lektor code https://github.com/lektor/lektor/blob/bc3064b8dc0c45b0c6274470c4d9a95e8bf4866c/lektor/imagetools.py#L434-L467 <https://github.com/lektor/lektor/blob/bc3064b8dc0c45b0c6274470c4d9a95e8bf4866c/lektor/imagetools.py#L434-L467> it seems to store the source where the images goes, maybe to prevent this consecutive triggering of the image build.
> 
As I understand it, this API was designed for thumbnail generation, where only one page requires the thumbnail and thus it makes sense to store the generated resource locally. Not sure how to best apply it for us.
> And thinking about making a more stable plugin that runs even offline, shipping the icons is probably the right approach to that.
> 
I should have some time tomorrow to give that a try, lets see how it goes.

**Comment by dwt** [comment]
Hey,  I have given this another shot, this time with local icons.

This seems to nicely solve the problem that the lektor build system didn't recognize when a file was up to date (though I'm still not completely sure I'm using it right).

What do you think? I'm using it and it seems to work - wich is at least something. :-)

**Comment by humrochagf** [comment]
Oh, this is really nice! Tested here with both python 3 and legacy and they all work.

Merging right now

**Pull request merged**
